[package]
name = "zcash-lib"
version = "0.1.0"
edition = "2024"
authors = ["dorianvp <dorianvp@zingolabs.org>"]

[dependencies]
bs58 = "0.5.1"
getrandom = "0.3.2"
k256 = "0.13.4"
ripemd = "0.1.3"
sha2 = "0.10.8"

[profile.dev.package."*"]
opt-level = 0
